name = "ai-code-review-agent"
compatibility_date = "2024-01-01"
pages_build_output_dir = "web-dist"

[env.production.vars]
AI_MODEL = "gpt-4o-mini"

# Environment variables are automatically available from Cloudflare Pages settings
# OPENAI_API_KEY - Set in Cloudflare Pages dashboard
# ANTHROPIC_API_KEY - Alternative API key (optional)

[vars]
AI_MODEL = "gpt-4o-mini"
